name: LockedStaff
version: '${project.version}'
main: com.lockeddevelopment.lockedstaff.LockedStaff
api-version: 1.19
authors: [ LockedDevelopment ]
description: StaffMode for customers

commands:
  lockedchat:
    description: For the customers (StaffChat)
  gmc:
    description: Gamemode Creative!
    permission: locked.creative
  bc:
    description: Broadcast Message!
    permission: locked.broadcast
  invsee:
    description: Invsee Command!
    permission: locked.invsee
  vanish:
    description: Vanish Command!
  gms:
    description: Gms Command!
    permission: locked.gms
  trade:
    description: Trade Command!